### ISSUE TITLE
Need to progress

### ISSUE THREAD

**Issue by qbolsee** [Walkerlikesfish/DSAP#1]
Hi pals,

Progress is going well, I'd say half of it is done. Can someone have a look at the Low pass filters?

Cheers.

**Comment by Walkerlikesfish** [comment]
Hi guys,
I have just updated the LMS and ADP upmix and LPF design, the LPF design has some problem, anyone check which matlab function to use? I know it is stupid question, but yeah...Anyhow

Cheers
